### ISSUE TITLE
ERROR in ./src/App.svelte Module not found: Error: Can't resolve 'svelte-iux' 

### ISSUE THREAD

**Issue by floresbakker** [theWebalyst/visualisation-lab#8]
Hi there happybeing,

This github seems very promising. As a newbee I tried downloading and installing the code. Pretty difficult as I don't have any knowledge about NPM, yarn and what not. I just know a little bit about RDF and its rich potential. I now got stuck during running  the code. 

This is the error message afterr typing "yarn dev". Before that I ran the installing of dependencies with "yarn" seemingly succesfully.

```
ERROR in ./src/App.svelte
Module not found: Error: Can't resolve 'svelte-iux' in 'C:\Users\JOHNSON\RDFPrograms\visualisation-lab-master\src'
 @ ./src/App.svelte 25:0-72 187:21-34 196:15-22
 @ ./src/main.js
 @ multi ./src/main.js

ERROR in ./src/viewmodels/ViewModelFoldsUI.svelte
Module not found: Error: Can't resolve 'svelte-iux' in 'C:\Users\JOHNSON\RDFPrograms\visualisation-lab-master\src\viewmodels'
 @ ./src/viewmodels/ViewModelFoldsUI.svelte 32:0-72 193:21-34 229:15-22 347:16-23 371:16-23
 @ ./src/App.svelte
 @ ./src/main.js
 @ multi ./src/main.js
i ｢wdm｣: Failed to compile.
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\swapfile.sys'
```
How should I proceed from here? I am greatly interested in the functionalities and eager to try it on my own RDF data...

Kind regards,

Flores

**Comment by happybeing** [comment]
I can't check precisely but I think you will need to do the following:
```
git clone https://github.com/happybeing/svelte-iux
```
Then in your visualisation-lab/src directory
```
ln -s <path-to-svelte-iux> svelte-iux
```
If that doesn't work let me know. I can't build at all at the moment!

**Comment by happybeing** [comment]
Having got it to build I can see I've used yarn link (you could use npm link, but I prefer yarn). So:

In the `svelte-iux/` directory do:
```
yarn link
```
In the `visualisation-lab/` directory do:
```
yarn link svelte-iux
```

I also needed to use NodeJs v14 for it to build, so if you still have problems I recommend using `nvm` (Node version manager) to install v14 and then in the `visualisation-lab/` directory do `nmv use 14`.

Good luck.

**Comment by floresbakker** [comment]
> Having got it to build I can see I've used yarn link (you could use npm link, but I prefer yarn). So:
> 
> In the `svelte-iux/` directory do:
> 
> ```
> yarn link
> ```
> 
> In the `visualisation-lab/` directory do:
> 
> ```
> yarn link svelte-iux
> ```
> 
> I also needed to use NodeJs v14 for it to build, so if you still have problems I recommend using `nvm` (Node version manager) to install v14 and then in the `visualisation-lab/` directory do `nmv use 14`.
> 
> Good luck.

This did the trick for me, thanks!
